name = "warden"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [{ pattern = "warden.run", custom_domain = true }]

[[workflows]]
name = "discovery-workflow"
binding = "DISCOVERY_WORKFLOW"
class_name = "DiscoveryWorkflow"

[vars]
KV_REST_API_URL = "https://quick-ladybird-14699.upstash.io"
WORKOS_CLIENT_ID = "client_01KD3FTW7R2QD0NW6QB7QP6Q0B"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "6a576a8480fb40b7a4b307bed14d9afc"
