name = "warden"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [{ pattern = "warden.run", custom_domain = true }]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "6a576a8480fb40b7a4b307bed14d9afc"
